### ISSUE TITLE
issues running updated brunnhilde on bitcurator

### ISSUE THREAD

**Issue by kellybolding** [tw4l/brunnhilde#58]
I ran the “sudo pip install brunnhilde --upgrade” command on my Bitcurator 1.8.2 machine since it looked like we were running an older version of Brunnhilde, and now I’m getting error messages when I try to call brunnhilde.py at all (screenshot attached). It seems like something might have gone wrong with the upgrade, but I’m not sure how to revert or fix.

Per email convo with Tessa: "I think what's happening is that the newest versions of the requests library require Python 3.7 or higher. And it looks like BitCurator is using Python 3.5. I suspect that it may be possible to simply remove requests at this point, since it was mostly being used to fetch CSS and JavaScript assets for the report that are no longer stored externally as of recent versions of Brunnhilde."

Thank you!! 

![post-update](https://user-images.githubusercontent.com/8289998/184145123-d1409617-4afb-4259-9d19-c6ec6795c57f.png)

**Comment by tw4l** [comment]
Hi @kellybolding! I just pushed release 1.9.5 of Brunnhilde, which removes the `requests` library and should solve your issue in BitCurator. `sudo pip install --upgrade brunnhilde` should work for you now in Python 3.5 :)

I'm closing the issue but feel free to re-open it if anything!

**Comment by kellybolding** [comment]
Hi @tw4l ! Thank you so much for working on this!!

I just tried it out, and I am unfortunately still getting error messages (screenshots included here). I noticed that the syntax of the command you mentioned in your comment is a bit different (`sudo pip install --upgrade brunnhilde` vs. `sudo pip install brunnhilde --upgrade`), so I tried it both ways and attached the messages I got for both in case it makes a difference (but I think the error messages are the same).

![try2](https://user-images.githubusercontent.com/8289998/185179877-ec479ec7-6080-4dd4-925d-7d45695d79f3.png)
![try1](https://user-images.githubusercontent.com/8289998/185179879-99bd7470-8935-43f4-a73e-797564ca5974.png)

If this seems like something that's particular to my installation, just let me know and I will take my troubleshooting efforts back locally. I appreciate your help in any case!

**Comment by tw4l** [comment]
Hi @kellybolding - I think perhaps the version of pip that's installed isn't compatible with Python 3.5. It looks like support for Python 3.5 was dropped in pip v21: https://pip.pypa.io/en/stable/news/#v21-0.

Try installing an older version of pip with `sudo pip install --force-reinstall pip==20.3.4`. Then I think you should be able to install the latest version of Brunnhilde.
